### ISSUE TITLE
Adapt to multiple class segmentation

### ISSUE THREAD

**Issue by panovr** [sdsubhajitdas/Brain-Tumor-Segmentation#12]
Hi,
  the original code is really a nice implementation of u-net architecture for binary class segmentation.
  May you consider to adapt this code for multiple class segmentation?
  Thanks!

**Comment by sdsubhajitdas** [comment]
Hi @panovr, 
I am sorry but I don't have the time and resources to adapt the code for multiple class segmentation. If you feel like working on this you are free to fork the project and work on this.
