### ISSUE TITLE
Brats Dataset

### ISSUE THREAD

**Issue by gusleo** [sdsubhajitdas/Brain-Tumor-Segmentation#3]
Hi, have try to run your code with Brats Dataset? what is need to make it run with your code

**Comment by sdsubhajitdas** [comment]
You need to have a folder structure example.
```
Dataset
 - 1.png
 - 1_mask.png
 - 2.png
 - 2_mask.png
 ......
```
Then use the ```bts``` package like 
```
from bts.dataset import TumorDataset
dobj = TumorDataset("dataset path root")
```
`TumorDataset` class is actually inherited from `torch.utils.data.Dataset`.
So I suggest you read this documentation part. 

https://pytorch.org/tutorials/beginner/data_loading_tutorial.html#
